name= input("what is your name user?")
print(f"hello{name} do you want to here some jokes")
input("")
print("what did the sushi say to the bee?")
input("")
print("wasabi")
input("")
print("why dont scientist trust atoms?")
input("")
print("Because they end in everything")
print("click enter for more jokes or leave!")
input("")
print("why did the scarecrow win an award")
input("")
print("because he was outstanding in his field")
print(f"thanks for listening to these dad jokes bye {name}!!")